from enum import StrEnum


class ResponseCode(StrEnum):
    OK = "OK"

    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Auth
    USERNAME_TAKEN = "USERNAME_TAKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_INVALID = "TOKEN_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"

    # KnowledgeBase
    KNOWLEDGE_BASE_NOT_FOUND = "KNOWLEDGE_BASE_NOT_FOUND"
    KNOWLEDGE_BASE_ACCESS_DENIED = "KNOWLEDGE_BASE_ACCESS_DENIED"

    # Source
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SOURCE_TYPE_UNSUPPORTED = "SOURCE_TYPE_UNSUPPORTED"
    SOURCE_CONFIG_INVALID = "SOURCE_CONFIG_INVALID"
    SOURCE_STATUS_INVALID = "SOURCE_STATUS_INVALID"

    # Upload
    UPLOAD_OBJECT_NOT_FOUND = "UPLOAD_OBJECT_NOT_FOUND"
    UPLOAD_FORBIDDEN_EXTENSION = "UPLOAD_FORBIDDEN_EXTENSION"
    UPLOAD_PRESIGN_FAILED = "UPLOAD_PRESIGN_FAILED"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"

    # Document
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_PARSE_ERROR = "DOCUMENT_PARSE_ERROR"
    DOCUMENT_UNSUPPORTED_FORMAT = "DOCUMENT_UNSUPPORTED_FORMAT"

    # Session
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_ACCESS_DENIED = "SESSION_ACCESS_DENIED"

    # Retrieval
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    QA_FAILED = "QA_FAILED"
    SEARCH_STRATEGY_UNKNOWN = "SEARCH_STRATEGY_UNKNOWN"

    # Studio
    STUDIO_TASK_NOT_FOUND = "STUDIO_TASK_NOT_FOUND"
    STUDIO_TASK_FAILED = "STUDIO_TASK_FAILED"
    STUDIO_TASK_NOT_COMPLETED = "STUDIO_TASK_NOT_COMPLETED"
