from enum import StrEnum


class ResponseCode(StrEnum):
    OK = "OK"

    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Auth
    USERNAME_TAKEN = "USERNAME_TAKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_INVALID = "TOKEN_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"

    # KnowledgeBase
    KNOWLEDGE_BASE_NOT_FOUND = "KNOWLEDGE_BASE_NOT_FOUND"
    KNOWLEDGE_BASE_ACCESS_DENIED = "KNOWLEDGE_BASE_ACCESS_DENIED"

    # Source
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SOURCE_TYPE_UNSUPPORTED = "SOURCE_TYPE_UNSUPPORTED"

    # Document
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_PARSE_ERROR = "DOCUMENT_PARSE_ERROR"
    DOCUMENT_UNSUPPORTED_FORMAT = "DOCUMENT_UNSUPPORTED_FORMAT"

    # Retrieval
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    QA_FAILED = "QA_FAILED"
