from app.services.studio.types import ChapterContent


def assemble_markdown(
    title: str,
    chapters: list[ChapterContent],
    style: str,
    length: str,
) -> str:
    toc_lines = [f"# {title}\n", "## Table of Contents\n"]
    for i, ch in enumerate(chapters, 1):
        toc_lines.append(f"{i}. [{ch.title}](#{_anchor(ch.title)})")
    toc = "\n".join(toc_lines)

    body_parts = []
    for ch in chapters:
        body_parts.append(ch.content)

    footer = _footer(style, length)

    return "\n\n".join([toc, *body_parts, footer])


def _anchor(heading: str) -> str:
    return heading.lower().replace(" ", "-").replace("/", "")


def _footer(style: str, length: str) -> str:
    from datetime import UTC, datetime

    return (
        "---\n\n"
        f"*Report generated by KnowledgeBase Studio · {style} style · {length} length*\n"
        f"*{datetime.now(UTC).strftime('%B %d, %Y')}*"
    )
