INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
HTTP_ERROR = "HTTP_ERROR"

USER_NOT_FOUND = "USER_NOT_FOUND"
USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"

TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
TEAM_NAME_EXISTS = "TEAM_NAME_EXISTS"

KNOWLEDGE_BASE_NOT_FOUND = "KNOWLEDGE_BASE_NOT_FOUND"
OWNER_NOT_IN_TEAM = "OWNER_NOT_IN_TEAM"

PERMISSION_DENIED = "PERMISSION_DENIED"

KNOWLEDGE_SOURCE_NOT_FOUND = "KNOWLEDGE_SOURCE_NOT_FOUND"
INDEX_JOB_NOT_FOUND = "INDEX_JOB_NOT_FOUND"
SOURCE_NOT_ACTIVE = "SOURCE_NOT_ACTIVE"
SOURCE_TYPE_NOT_SUPPORTED = "SOURCE_TYPE_NOT_SUPPORTED"
SOURCE_CONFIG_INVALID = "SOURCE_CONFIG_INVALID"
SOURCE_PATH_NOT_FOUND = "SOURCE_PATH_NOT_FOUND"
