INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
HTTP_ERROR = "HTTP_ERROR"

USER_NOT_FOUND = "USER_NOT_FOUND"
USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"

TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
TEAM_NAME_EXISTS = "TEAM_NAME_EXISTS"

KNOWLEDGE_BASE_NOT_FOUND = "KNOWLEDGE_BASE_NOT_FOUND"
OWNER_NOT_IN_TEAM = "OWNER_NOT_IN_TEAM"

PERMISSION_DENIED = "PERMISSION_DENIED"
